openapi: 3.2.0
info:
  version: 1.3.0
  title: Xe.Api.Payments Purposes Of Payment API
tags:
- name: PurposesOfPayment
paths:
  /purposesofpayment/{currency}:
    get:
      tags:
      - PurposesOfPayment
      summary: Get purposes of payment for given user.
      description: "Sample request:\n\n    Get /purposesofpayment/INR\n\n\\\n<details><summary>**The complete set of purposes of payment for all currencies are**</summary>\n* BONUS_SALARY\n* CORP_BONUS\n* CORP_CHARITY\n* CORP_CUSTOMER_PAYMENT\n* CORP_DIVIDEND\n* CORP_EMPLOYEE_EXPENSES\n* CORP_FREIGHT\n* CORP_IMPORT_EXPORT\n* CORP_INR_BANKERS\n* CORP_INR_COOP\n* CORP_INR_CREDIT\n* CORP_INR_EDUCATIONAL\n* CORP_INR_EMI\n* CORP_INR_FAMILIES\n* CORP_INR_POSTMASTER\n* CORP_INR_TAX\n* CORP_INR_TRADE\n* CORP_INR_TRAVEL\n* CORP_INR_UTILTY\n* CORP_INSURANCE\n* CORP_INVESTMENT\n* CORP_INVOICE\n* CORP_OPERATING_COST\n* CORP_OTHER\n* CORP_OUTSOURCING\n* CORP_PENSION\n* CORP_PROPERTY_BUY_SELL\n* CORP_PROPERTY_MANAGEMENT\n* CORP_REPATRIATION\n* CORP_SALARY\n* CORP_SUPPLIER_PAYMENT\n* CORP_TAX\n* CORP_TRAVEL_SERVICES\n* DIVIDEND_PAYMENT\n* EXPENSES\n* INSURANCE_CLAIMS\n* INVOICES\n* OTHER\n* PENSION\n* PRIV_BILL_PAYMENT\n* PRIV_BUSINESS_PAYMENT\n* PRIV_CHARITY\n* PRIV_FAMILY_SUPPORT\n* PRIV_GIFT\n* PRIV_GOODS_SERVICES\n* PRIV_HOLIDAY\n* PRIV_INHERITANCE\n* PRIV_INR_BANKERS\n* PRIV_INR_COOP\n* PRIV_INR_CREDIT\n* PRIV_INR_EDUCATIONAL\n* PRIV_INR_EMI\n* PRIV_INR_FAMILIES\n* PRIV_INR_HOTELS\n* PRIV_INR_MEDICAL\n* PRIV_INR_POSTMASTER\n* PRIV_INR_TAX\n* PRIV_INR_TRADE\n* PRIV_INR_TRAVEL\n* PRIV_INR_UTILTY\n* PRIV_INVESTMENT\n* PRIV_LIVING\n* PRIV_LOAN_REPAYMENT\n* PRIV_MEDICAL\n* PRIV_MORTGAGE\n* PRIV_OTHER\n* PRIV_PENSION\n* PRIV_PROPERTY_BUY_SELL\n* PRIV_RELOCATION\n* PRIV_SALARY\n* PRIV_TAX\n* PRIV_TEST_TRANSFER\n* PRIV_TRAVEL_EXPENSES\n* PRIV_TRAVEL_MONEY\n* PRIV_TUITION\n* PRIV_WEDDING\n* PROPERTY_MANAGEMENT\n* SALARY\n* SUPPLIERS\n* TAX\n* TEMPORARY_CODE_102\n* TEMPORARY_CODE_103\n* TRAVEL_SERVICES\n</details>"
      operationId: Get
      parameters:
      - name: currency
        in: path
        description: Currency code to get purposes of payment for.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Returns list of purposes of payment.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurposeOfPaymentListResponse'
              example:
                content:
                - code: PRIV_BILL_PAYMENT
                  allowFreeText: true
        '400':
          description: Purposes of payment not found for this user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurposeOfPaymentListResponse'
              example:
                message: Request failed validation.
                errors:
                - code: CURRENCY_VALIDATION
                  data:
                  - key: currency
                    value: Currency is required.
        '500':
          description: Error getting purposes of payment for this user.
components:
  schemas:
    PurposeOfPaymentListResponse:
      description: "Generic response returned for each request.\n            \n\"message\" - Result from the request.\n\"content\" - Data returned in the response.\n\"errors\" - Issues while processing the request.\n\"warnings\" - Potential issues while processing the request or with the response data.\n\"information\" - Extra details relating to the response data.\n<typeparam name=\"T\">The type of the content.</typeparam>"
      type: object
      properties:
        content:
          uniqueItems: false
          type: array
          items:
            $ref: '#/components/schemas/PurposeOfPayment'
        message:
          type: string
        errors:
          uniqueItems: false
          type: array
          items:
            $ref: '#/components/schemas/Message'
        warnings:
          uniqueItems: false
          type: array
          items:
            $ref: '#/components/schemas/Message'
        information:
          uniqueItems: false
          type: array
          items:
            $ref: '#/components/schemas/Message'
    Message:
      description: "Details for an error or warning that occured during the request or general information from it.\n            \n\"code\" - Code that can be used to find full details for the message.\n\"data\" - Any relevant data that caused the message, if applicable."
      type: object
      properties:
        code:
          type: string
        data:
          uniqueItems: false
          type: array
          items:
            $ref: '#/components/schemas/StringStringKeyValuePair'
    PurposeOfPayment:
      type: object
      properties:
        code:
          type: string
        allowFreeText:
          type: boolean
    StringStringKeyValuePair:
      type: object
      properties:
        key:
          type: string
          readOnly: true
        value:
          type: string
          readOnly: true
