openapi: 3.2.0
info:
  version: 0.4.1
  title: Xe.Api.MassPayments Terms API
tags:
- name: Terms
paths:
  /terms:
    get:
      tags:
      - Terms
      summary: Gets the important information relating to making a transaction.
      description: 'Sample request:


        GET /terms'
      operationId: Get
      responses:
        '200':
          description: Returns the important information.
        '500':
          description: Error getting the important information.
