openapi: 3.2.0
info:
  description: This is a simple API
  version: 1.0.0
  title: XE Currency Data Tradable Rates API
servers:
- url: https://virtserver.swaggerhub.com/XE.com/xecdapi-tradable/1.0.0
tags:
- name: tradable-rates
  description: Tradable rates API
paths:
  /tradeable_rate:
    get:
      tags:
      - tradable-rates
      summary: get tradable rates
      operationId: getTradableRate
      description: 'Get tradable rates

        '
      parameters:
      - in: query
        name: sell
        description: currency symbol (e.g. CAD) to be sold
        required: true
        schema:
          type: string
      - in: query
        name: buy
        description: currency symbol (e.g. USD) to be bought
        required: true
        schema:
          type: string
      - in: query
        name: amount
        description: amount of currencies to sell
        schema:
          type: number
          format: double64
          minimum: 0
      - in: query
        name: country
        description: country code (e.g. CA) where the client resides
        required: true
        schema:
          type: string
      - in: query
        name: account_type
        description: type of client account, either PRIVATE or CORPORATE
        required: true
        schema:
          type: string
      - in: query
        name: fixed_currency
        description: which currency for the amount parameter, either "sell" or "buy"
        required: false
        schema:
          type: string
      responses:
        '200':
          description: tradable rate for the specific currency
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/TradableRatesResponse'
        '400':
          description: bad input parameter
        '403':
          description: no access to this endpoint
components:
  schemas:
    TradableRatesResponse:
      type: object
      required:
      - buyAmount
      - sellAmount
      - buy
      - sell
      - rate
      - fixedCurrency
      - terms
      - privacy
      properties:
        buyAmount:
          type: number
          format: double64
          example: 76.11
          description: amount of currency to be bought
        sellAmount:
          type: number
          format: double64
          example: 100
          description: amount of currency to be sold
        buy:
          type: string
          example: USD
          description: currency to be bought
        sell:
          type: string
          example: CAD
          description: currency to be sold
        rate:
          type: number
          example: 0.76108
          description: tradable exchange rate between buy and sell currencies
        fixedCurrency:
          type: string
          example: CAD
          description: currency for "amount" parameter
