openapi: 3.2.0
info:
  version: 1.3.0
  title: Xe.Api.Payments Purposes Of Payment API
tags:
- name: PurposesOfPayment
paths:
  /purposesofpayment/{currency}:
    get:
      tags:
      - PurposesOfPayment
      summary: Get purposes of payment for given user
      description: 'Sample request:


        Get /purposesofpayment/INR


        \

        **The complete set of purposes of payment for all currencies are**

        * BONUS_SALARY

        * CORP_BONUS

        * CORP_CHARITY

        * CORP_CUSTOMER_PAYMENT

        * CORP_DIVIDEND

        * CORP_EMPLOYEE_EXPENSES

        * CORP_FREIGHT

        * CORP_IMPORT_EXPORT

        * CORP_INR_BANKERS

        * CORP_INR_COOP

        * CORP_INR_CREDIT

        * CORP_INR_EDUCATIONAL

        * CORP_INR_EMI

        * CORP_INR_FAMILIES

        * CORP_INR_POSTMASTER

        * CORP_INR_TAX

        * CORP_INR_TRADE

        * CORP_INR_TRAVEL

        * CORP_INR_UTILTY

        * CORP_INSURANCE

        * CORP_INVESTMENT

        * CORP_INVOICE

        * CORP_OPERATING_COST

        * CORP_OTHER

        * CORP_OUTSOURCING

        * CORP_PENSION

        * CORP_PROPERTY_BUY_SELL

        * CORP_PROPERTY_MANAGEMENT

        * CORP_REPATRIATION

        * CORP_SALARY

        * CORP_SUPPLIER_PAYMENT

        * CORP_TAX

        * CORP_TRAVEL_SERVICES

        * DIVIDEND_PAYMENT

        * EXPENSES

        * INSURANCE_CLAIMS

        * INVOICES

        * OTHER

        * PENSION

        * PRIV_BILL_PAYMENT

        * PRIV_BUSINESS_PAYMENT

        * PRIV_CHARITY

        * PRIV_FAMILY_SUPPORT

        * PRIV_GIFT

        * PRIV_GOODS_SERVICES

        * PRIV_HOLIDAY

        * PRIV_INHERITANCE

        * PRIV_INR_BANKERS

        * PRIV_INR_COOP

        * PRIV_INR_CREDIT

        * PRIV_INR_EDUCATIONAL

        * PRIV_INR_EMI

        * PRIV_INR_FAMILIES

        * PRIV_INR_HOTELS

        * PRIV_INR_MEDICAL

        * PRIV_INR_POSTMASTER

        * PRIV_INR_TAX

        * PRIV_INR_TRADE

        * PRIV_INR_TRAVEL

        * PRIV_INR_UTILTY

        * PRIV_INVESTMENT

        * PRIV_LIVING

        * PRIV_LOAN_REPAYMENT

        * PRIV_MEDICAL

        * PRIV_MORTGAGE

        * PRIV_OTHER

        * PRIV_PENSION

        * PRIV_PROPERTY_BUY_SELL

        * PRIV_RELOCATION

        * PRIV_SALARY

        * PRIV_TAX

        * PRIV_TEST_TRANSFER

        * PRIV_TRAVEL_EXPENSES

        * PRIV_TRAVEL_MONEY

        * PRIV_TUITION

        * PRIV_WEDDING

        * PROPERTY_MANAGEMENT

        * SALARY

        * SUPPLIERS

        * TAX

        * TEMPORARY_CODE_102

        * TEMPORARY_CODE_103

        * TRAVEL_SERVICES'
      operationId: Get
      parameters:
      - name: currency
        in: path
        description: Currency code to get purposes of payment for.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Returns list of purposes of payment.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurposeOfPaymentListResponse'
              example:
                content:
                - code: PRIV_BILL_PAYMENT
                  allowFreeText: true
        '400':
          description: Purposes of payment not found for this user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurposeOfPaymentListResponse'
              example:
                message: Request failed validation.
                errors:
                - code: CURRENCY_VALIDATION
                  data:
                  - key: currency
                    value: Currency is required.
        '500':
          description: Error getting purposes of payment for this user.
components:
  schemas:
    Message:
      description: "Details for an error or warning that occured during the request or general information from it.\n            \n\"code\" - Code that can be used to find full details for the message.\n\"data\" - Any relevant data that caused the message, if applicable."
      type: object
      properties:
        code:
          type: string
        data:
          uniqueItems: false
          type: array
          items:
            $ref: '#/components/schemas/StringStringKeyValuePair'
    StringStringKeyValuePair:
      type: object
      properties:
        key:
          type: string
          readOnly: true
        value:
          type: string
          readOnly: true
    PurposeOfPaymentListResponse:
      description: "Generic response returned for each request.\n            \n\"message\" - Result from the request.\n\"content\" - Data returned in the response.\n\"errors\" - Issues while processing the request.\n\"warnings\" - Potential issues while processing the request or with the response data.\n\"information\" - Extra details relating to the response data.\n<typeparam name=\"T\">The type of the content.</typeparam>"
      type: object
      properties:
        content:
          uniqueItems: false
          type: array
          items:
            $ref: '#/components/schemas/PurposeOfPayment'
        message:
          type: string
        errors:
          uniqueItems: false
          type: array
          items:
            $ref: '#/components/schemas/Message'
        warnings:
          uniqueItems: false
          type: array
          items:
            $ref: '#/components/schemas/Message'
        information:
          uniqueItems: false
          type: array
          items:
            $ref: '#/components/schemas/Message'
    PurposeOfPayment:
      type: object
      properties:
        code:
          type: string
        allowFreeText:
          type: boolean
